### ISSUE TITLE
Baseline search says it is misconfigured when I try to add mutations

### ISSUE THREAD

**Issue by anna-parker** [GenSpectrum/dashboards#413]
![image](https://github.com/user-attachments/assets/d98faed2-95a4-432a-91d1-c6cb5d1836f5)
```
hoisted.BDwTRF8J.js:100 InvalidPropsError: [
  {
    "code": "invalid_union",
    "unionErrors": [
      {
        "issues": [
          {
            "code": "invalid_type",
            "expected": "object",
            "received": "array",
            "path": [
              "numeratorFilter"
            ],
            "message": "Expected object, received array"
          }
        ],
        "name": "ZodError"
      },
      {
        "issues": [
          {
            "code": "invalid_union",
            "unionErrors": [
              {
                "issues": [
                  {
                    "code": "invalid_type",
                    "expected": "string",
                    "received": "array",
                    "path": [
                      "numeratorFilter",
                      0,
                      "lapisFilter",
                      "nucleotideMutations"
                    ],
                    "message": "Expected string, received array"
                  }
                ],
                "name": "ZodError"
              },
              {
                "issues": [
                  {
                    "code": "invalid_type",
                    "expected": "number",
                    "received": "array",
                    "path": [
                      "numeratorFilter",
                      0,
                      "lapisFilter",
                      "nucleotideMutations"
                    ],
                    "message": "Expected number, received array"
                  }
                ],
                "name": "ZodError"
              },
              {
                "issues": [
                  {
                    "code": "invalid_type",
                    "expected": "null",
                    "received": "array",
                    "path": [
                      "numeratorFilter",
                      0,
                      "lapisFilter",
                      "nucleotideMutations"
                    ],
                    "message": "Expected null, received array"
                  }
                ],
                "name": "ZodError"
              },
              {
                "issues": [
                  {
                    "code": "invalid_type",
                    "expected": "boolean",
                    "received": "array",
                    "path": [
                      "numeratorFilter",
                      0,
                      "lapisFilter",
                      "nucleotideMutations"
                    ],
                    "message": "Expected boolean, received array"
                  }
                ],
                "name": "ZodError"
              }
            ],
            "path": [
              "numeratorFilter",
              0,
              "lapisFilter",
              "nucleotideMutations"
            ],
            "message": "Invalid input"
          }
        ],
        "name": "ZodError"
      }
    ],
    "path": [
      "numeratorFilter"
    ],
    "message": "Invalid input"
  }
]
    at hoisted.BDwTRF8J.js:100:3953
    at fe (hoisted.BDwTRF8J.js:98:6538)
    at qG (hoisted.BDwTRF8J.js:100:3868)
    at Ts.Ce [as constructor] (hoisted.BDwTRF8J.js:100:3685)
    at Ts.jA [as render] (hoisted.BDwTRF8J.js:51:9907)
    at Tg (hoisted.BDwTRF8J.js:51:7045)
    at eC (hoisted.BDwTRF8J.js:51:2608)
    at Tg (hoisted.BDwTRF8J.js:51:7265)
    at eC (hoisted.BDwTRF8J.js:51:2608)
    at Tg (hoisted.BDwTRF8J.js:51:7265)
```

**Comment by fengelniederhammer** [comment]
Since you're the administrator of the page: What does the browser console say? ;)

**Comment by anna-parker** [comment]
This is now fixed, maybe one of the recent refactors also fixed it: 
![image](https://github.com/user-attachments/assets/0eeddc81-07df-4f99-9359-8a93021f5e53) - closing for now
